# Generated by Django 4.2.24 on 2025-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва тегу')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тег товару',
                'verbose_name_plural': 'Теги товарів',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Новий товар', verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, help_text='Топ товар', verbose_name='Топ'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_3_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна при покупці від 3 штук', max_digits=10, null=True, verbose_name='Ціна від 3 шт'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_5_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна при покупці від 5 штук', max_digits=10, null=True, verbose_name='Ціна від 5 шт'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортування'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги для фільтрації товарів', to='products.producttag', verbose_name='Теги'),
        ),
    ]
