# Generated by Django 4.2.24 on 2025-10-03 14:53

from django.db import migrations


def create_categories(apps, schema_editor):
    """Створення основних категорій товарів"""
    Category = apps.get_model('products', 'Category')
    
    # Спочатку видаляємо всі існуючі категорії
    Category.objects.all().delete()
    
    # Список категорій у правильному порядку
    categories_data = [
        ('Акційні товари', 'sale', 1),
        ('Нігті', 'nigti', 2),
        ('Волосся', 'volossia', 3),
        ('Брови та вії', 'brovy-ta-vii', 4),
        ('Депіляція', 'depilyatsiya', 5),
        ('Косметика', 'kosmetyka', 6),
        ('Макіяж', 'makiyazh', 7),
        ('Одноразова продукція', 'odnorazova-produktsia', 8),
        ('Дезінфекція та стерилізація', 'dezinfektsiya-ta-sterylizatsiya', 9),
        ('Меблі для салонів', 'mebli-dlya-saloniv', 10),
    ]
    
    # Створюємо категорії
    for name, slug, sort_order in categories_data:
        Category.objects.create(
            name=name,
            slug=slug,
            sort_order=sort_order,
            is_active=True,
            parent=None
        )


def remove_categories(apps, schema_editor):
    """Видалення категорій при rollback"""
    Category = apps.get_model('products', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttag_product_is_new_product_is_top_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
