# Generated by Django 4.2.24 on 2025-10-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_recommendedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.DecimalField(decimal_places=2, help_text='Нова ціна для акційної пропозиції', max_digits=10, verbose_name='Акційна ціна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Акційна пропозиція',
                'verbose_name_plural': 'Акційні пропозиції',
                'ordering': ['sort_order', '-created_at'],
                'unique_together': {('product',)},
            },
        ),
    ]
