# Generated by Django 4.2.24 on 2025-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_sale_periods_and_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID категорії в системі постачальника', max_length=50, null=True, unique=True, verbose_name='Зовнішній ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Артикул постачальника (vendorCode)', max_length=50, null=True, verbose_name='Зовнішній ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Назва бренду/постачальника з фіду', max_length=200, verbose_name='Постачальник'),
        ),
    ]
