# Generated by Django 4.2.21 on 2025-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_brand_review'),
    ]

    operations = [
        # Видаляємо індекси перед видаленням полів
        migrations.RemoveIndex(
            model_name='productchangelog',
            name='products_pr_product_f2fdac_idx',
        ),
        migrations.RemoveIndex(
            model_name='productchangelog',
            name='products_pr_change__b042da_idx',
        ),
        migrations.RemoveIndex(
            model_name='salepromotion',
            name='products_sa_is_acti_ab1021_idx',
        ),
        
        # Тепер видаляємо поля
        migrations.RemoveField(
            model_name='categoryfilterconfig',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productchangelog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productchangelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.DeleteModel(
            name='ProductPurpose',
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promotionproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salepromotion',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='salepromotion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salepromotion',
            name='products',
        ),
        migrations.DeleteModel(
            name='CategoryFilterConfig',
        ),
        migrations.DeleteModel(
            name='NewProduct',
        ),
        migrations.DeleteModel(
            name='ProductChangeLog',
        ),
        migrations.DeleteModel(
            name='PromotionProduct',
        ),
        migrations.DeleteModel(
            name='SalePromotion',
        ),
    ]
