# Generated by Django 4.2.21 on 2025-10-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimage_image_url_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, help_text='Акція автоматично завершиться після цієї дати', null=True, verbose_name='Дата закінчення акції'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start_date',
            field=models.DateTimeField(blank=True, help_text='Залиште порожнім для необмеженої акції', null=True, verbose_name='Дата початку акції'),
        ),
    ]
