# Generated by Django 4.2.21 on 2025-10-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_sale_end_date_product_sale_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Акційна пропозиція',
                'verbose_name_plural': 'Акційні пропозиції',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
