# Generated by Django 4.2.21 on 2025-10-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_saleproduct_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва акції')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток від ціни'), ('fixed', 'Фіксована знижка')], default='percentage', max_length=20, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розмір знижки')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата закінчення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('categories', models.ManyToManyField(blank=True, help_text='Оберіть категорії для застосування знижки', to='products.category', verbose_name='Категорії')),
                ('products', models.ManyToManyField(blank=True, help_text='Оберіть конкретні товари для застосування знижки', to='products.product', verbose_name='Товари')),
            ],
            options={
                'verbose_name': 'Акційна пропозиція',
                'verbose_name_plural': 'Акційні пропозиції',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SaleProduct',
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='products_sa_is_acti_6de77d_idx'),
        ),
    ]
