# Generated by Django 4.2.21 on 2025-10-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productreview_sale_delete_saleproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_name',
            field=models.CharField(blank=True, default='', help_text='Назва акції для відображення на стікері', max_length=200, verbose_name='Назва акції'),
        ),
    ]
