# Generated by Django 4.2.21 on 2025-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_sale_name_productreview'),
    ]

    operations = [
        # Додаємо індекси для пошуку
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='products_pr_is_acti_69be20_idx'),
        ),
    ]
