# Generated by Django 4.2.21 on 2025-11-03 11:43

from django.db import migrations, models, connection
import django.db.models.deletion


def check_table_exists(table_name):
    """Перевіряє чи існує таблиця"""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [table_name])
        else:
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name=%s;
            """, [table_name])
        result = cursor.fetchone()
        return result and result[0]


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_merge_20241102_1412'),
    ]

    operations = []
    
    # ProductReview: перевіряємо чи існує, створюємо тільки якщо немає
    if not check_table_exists('products_productreview'):
        operations.append(
            migrations.CreateModel(
                name='ProductReview',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('author_name', models.CharField(default='Аноним', max_length=100, verbose_name="Ім'я автора")),
                    ('rating', models.PositiveSmallIntegerField(default=5, help_text='Оцінка від 1 до 5', verbose_name='Рейтинг')),
                    ('text', models.TextField(verbose_name='Текст відгуку')),
                    ('category_badge', models.CharField(blank=True, help_text='Наприклад: "Піхва", "Вакуумні стимулятори"', max_length=50, verbose_name='Бейдж категорії')),
                    ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                    ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ],
                options={
                    'verbose_name': 'Відгук про товар',
                    'verbose_name_plural': 'Відгуки про товари',
                    'ordering': ['-created_at'],
                },
            )
        )
    
    # TopProduct: завжди створюємо (нова модель)
    operations.extend([
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Лідер продажу',
                'verbose_name_plural': 'Лідери продажу',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji або CSS клас', max_length=50, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Категорія для URL та основного відображення', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='products.category', verbose_name='Основна категорія'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['primary_category', 'is_active'], name='products_pr_primary_f7e607_idx'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='product',
            field=models.OneToOneField(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='top_product_entry', to='products.product', verbose_name='Товар'),
        ),
    ])
    
    # Додаємо індекси для ProductReview тільки якщо таблиця існує
    if check_table_exists('products_productreview'):
        operations.extend([
            migrations.RunSQL(
                sql="ALTER TABLE products_productreview ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES products_product(id) ON DELETE CASCADE;",
                reverse_sql=migrations.RunSQL.noop
            ),
        ])
