# Generated by Django 4.2.21 on 2025-11-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_merge_20241102_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('product', models.OneToOneField(
                    limit_choices_to={'is_active': True},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='top_product_entry',
                    to='products.product',
                    verbose_name='Товар'
                )),
            ],
            options={
                'verbose_name': 'Лідер продажу',
                'verbose_name_plural': 'Лідери продажу',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Аноним', max_length=100, verbose_name="Ім'я автора")),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Оцінка від 1 до 5', verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('category_badge', models.CharField(blank=True, max_length=50, verbose_name='Бейдж категорії', help_text='Наприклад: "Піхва", "Вакуумні стимулятори"')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to='products.product',
                    verbose_name='Товар'
                )),
            ],
            options={
                'verbose_name': 'Відгук про товар',
                'verbose_name_plural': 'Відгуки про товари',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['is_approved', '-created_at'], name='products_pr_is_appr_b55fbf_idx'),
                    models.Index(fields=['product', 'is_approved'], name='products_pr_product_160d92_idx'),
                ],
            },
        ),
    ]

