# Generated by Django 4.2.21 on 2025-11-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_topproduct_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_50f5f1_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji або CSS клас', max_length=50, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Категорія для URL та основного відображення', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='products.category', verbose_name='Основна категорія'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['primary_category', 'is_active'], name='products_pr_primary_f7e607_idx'),
        ),
    ]
