# Generated by Django 4.2.21 on 2025-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_delete_brand_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_main'], name='products_pr_product_a6a200_idx'),
        ),
    ]
