# Generated by Django 4.2.21 on 2025-11-19 18:16

from django.db import migrations, models, connection
import django.db.models.deletion
from django.db.models import Count


def remove_duplicate_products(apps, schema_editor):
    """Видаляє дублікати Product.external_id перед додаванням unique constraint"""
    Product = apps.get_model('products', 'Product')
    
    # Знаходимо дублікати по external_id
    duplicates = Product.objects.values('external_id').annotate(
        count=Count('id')
    ).filter(count__gt=1, external_id__isnull=False)
    
    removed_count = 0
    for dup in duplicates:
        ext_id = dup['external_id']
        # Залишаємо найстаріший товар, видаляємо інші
        products = Product.objects.filter(external_id=ext_id).order_by('created_at')
        for product in products[1:]:
            product.delete()
            removed_count += 1
    
    if removed_count > 0:
        print(f'Видалено {removed_count} дублікатів товарів')


def drop_existing_unique_constraint(apps, schema_editor):
    """Видаляє існуючий unique constraint якщо є"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'products_product' 
            AND constraint_type = 'UNIQUE' 
            AND constraint_name LIKE '%external_id%';
        """)
        constraints = cursor.fetchall()
        for constraint in constraints:
            constraint_name = constraint[0]
            print(f'Видаляю constraint: {constraint_name}')
            cursor.execute(f'ALTER TABLE products_product DROP CONSTRAINT IF EXISTS {constraint_name};')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productimage_products_pr_product_a6a200_idx'),
    ]

    operations = [
        # КРОК 0: Видалити існуючі constraints
        migrations.RunPython(
            code=drop_existing_unique_constraint,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # КРОК 1: Видалити дублікати перед додаванням unique
        migrations.RunPython(
            code=remove_duplicate_products,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # КРОК 2: Змінити Category.parent на SET_NULL
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Батьківська категорія'),
        ),
        
        # КРОК 3: Додати unique constraint до Product.external_id
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Артикул постачальника (vendorCode)', max_length=50, null=True, unique=True, verbose_name='Зовнішній ID'),
        ),
    ]
