# Generated by Django 4.2.21 on 2025-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_fix_external_id_unique'),
    ]

    operations = [
        # Індекс для швидкого пошуку активних категорій з батьківською
        migrations.AddIndex(
            model_name='category',
            index=models.Index(
                fields=['is_active', 'parent'], 
                name='cat_active_parent_idx'
            ),
        ),
        # Індекс для швидкого сортування по retail_price
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['is_active', 'retail_price'], 
                name='prod_active_price_idx'
            ),
        ),
        # Індекс для швидкого пошуку в наявності
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['is_active', 'stock'], 
                name='prod_active_stock_idx'
            ),
        ),
    ]
