# Generated by Django 4.2.24 on 2025-09-27 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна підписка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата підписки')),
            ],
            options={
                'verbose_name': 'Підписка на розсилку',
                'verbose_name_plural': 'Підписки на розсилку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_method', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('courier', "Кур'єр"), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Спосіб доставки')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Місто доставки')),
                ('delivery_address', models.TextField(verbose_name='Адреса доставки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість доставки')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка при отриманні'), ('card', 'Оплата карткою'), ('bank_transfer', 'Банківський переказ'), ('liqpay', 'LiqPay')], max_length=20, verbose_name='Спосіб оплати')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума товарів')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки до замовлення')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Примітки адміна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва акції')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума'), ('free_shipping', 'Безкоштовна доставка')], max_length=20, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розмір знижки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мінімальна сума замовлення')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість використань')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Кількість використань')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата закінчення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в замовленні',
                'verbose_name_plural': 'Товари в замовленні',
            },
        ),
    ]
