# Generated by Django 4.2.24 on 2025-10-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttag_product_is_new_product_is_top_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Зображення банера')),
                ('link_type', models.CharField(choices=[('category', 'Категорія'), ('product', 'Товар'), ('promotion', 'Акція'), ('custom', 'Довільне посилання')], max_length=20, verbose_name='Тип посилання')),
                ('custom_url', models.URLField(blank=True, verbose_name='Довільне посилання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категорія')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.promotion', verbose_name='Акція')),
            ],
            options={
                'verbose_name': 'Банер акції',
                'verbose_name_plural': 'Банери акцій',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
