# Generated by Django 4.2.24 on 2025-10-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promotionbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionBanner',
        ),
    ]
