# Generated by Django 4.2.24 on 2025-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_promotion_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monobank_parts',
            field=models.BooleanField(default=False, verbose_name='Оплата частинами Monobank'),
        ),
        migrations.AddField(
            model_name='order',
            name='nova_poshta_ttn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ТТН Нової Пошти'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='LiqPay або Monobank', max_length=100, verbose_name='ID платежу'),
        ),
    ]
