# Generated by Django 4.2.21 on 2025-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_saleproduct_productreview'),
        ('orders', '0004_order_monobank_parts_order_nova_poshta_ttn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоди'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_to',
            field=models.CharField(choices=[('all', 'Всі товари'), ('non_sale', 'Тільки не акційні'), ('categories', 'Обрані категорії')], default='all', max_length=20, verbose_name='Застосувати до'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Категорії на які діє промокод (якщо обрано "Обрані категорії")', to='products.category', verbose_name='Категорії'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Відсоток від суми'), ('fixed', 'Фіксована знижка')], default='percentage', max_length=20, verbose_name='Тип знижки'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(help_text='Промокод автоматично завершиться', verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Залиште порожнім для необмеженої кількості', null=True, verbose_name='Максимальна кількість використань'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Залиште 0 якщо без обмежень', max_digits=10, verbose_name='Мінімальна сума замовлення'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва промокоду'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(help_text='Промокод стане активним з цієї дати', verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Кількість використань'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code', 'is_active'], name='orders_prom_code_43571b_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='orders_prom_start_d_df42d2_idx'),
        ),
    ]
