# Generated by Django 4.2.21 on 2025-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_promotion_options_promotion_apply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(help_text='Код який вводить покупець (наприклад: SUMMER2024). Буде автоматично конвертовано у верхній регістр', max_length=50, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(help_text='Описова назва для внутрішнього використання (наприклад: "Літня розпродаж 2024")', max_length=200, verbose_name='Назва промокоду'),
        ),
    ]
