# Generated by Django 4.2.21 on 2025-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_convert_promocodes_to_uppercase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Підсумкова сума'),
        ),
        migrations.AddField(
            model_name='order',
            name='nova_poshta_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто (НП)'),
        ),
        migrations.AddField(
            model_name='order',
            name='nova_poshta_warehouse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Відділення/Поштомат (НП)'),
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка на товари'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка промокоду'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_retail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Повна сума товарів'),
        ),
        migrations.AddField(
            model_name='order',
            name='ukrposhta_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адреса (Укрпошта)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ukrposhta_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто (Укрпошта)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ukrposhta_index',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індекс (Укрпошта)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта')], max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Оплата на сайті'), ('cash_on_delivery', 'Оплата при отриманні')], max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
