# Generated by Django 4.2.21 on 2026-02-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_payment_integration_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_payment_intent_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='nova_poshta_city_ref',
            field=models.CharField(blank=True, help_text='Унікальний ідентифікатор міста з API НП', max_length=100, verbose_name='Місто REF (НП)'),
        ),
        migrations.AddField(
            model_name='order',
            name='nova_poshta_warehouse_ref',
            field=models.CharField(blank=True, help_text='Унікальний ідентифікатор відділення з API НП', max_length=100, verbose_name='Відділення REF (НП)'),
        ),
    ]
