# Generated by Django 4.2.24 on 2025-10-06 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва для ідентифікації в адмін панелі', max_length=200, verbose_name='Назва банера')),
                ('desktop_image', models.ImageField(help_text='Розмір: 1200×400 пікселів (співвідношення 3:1)', upload_to='banners/desktop/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Зображення для десктопу')),
                ('mobile_image', models.ImageField(help_text='Розмір: 375×200 пікселів (співвідношення 1.875:1)', upload_to='banners/mobile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Зображення для мобільного')),
                ('link_url', models.URLField(blank=True, help_text='URL на який переходити при натисканні на банер', null=True, verbose_name='Посилання')),
                ('alt_text', models.CharField(default='Банер RedRabbit', help_text='Текст для accessibility та SEO', max_length=255, verbose_name='Alt текст')),
                ('is_active', models.BooleanField(default=True, help_text='Показувати банер на сайті', verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, help_text='Менше число = вище в списку', verbose_name='Порядок сортування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
