# Generated by Django 4.2.24 on 2025-10-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(help_text='Розмір: 375×280 пікселів (співвідношення 1.34:1)', upload_to='banners/mobile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Зображення для мобільного'),
        ),
    ]
