# Generated by Django 4.2.21 on 2025-11-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(default='Банер RedRabbit', help_text='Текст для accessibility та SEO', max_length=255, verbose_name='Alt текст'),
        ),
    ]
