# Generated by Django 4.2.21 on 2025-12-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_banner_alt_text_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Описова назва для ідентифікації', max_length=200, verbose_name='Назва пікселя')),
                ('pixel_type', models.CharField(choices=[('facebook', 'Facebook Pixel'), ('google_analytics', 'Google Analytics'), ('google_tag_manager', 'Google Tag Manager'), ('custom', 'Custom Pixel')], max_length=50, verbose_name='Тип пікселя')),
                ('pixel_id', models.CharField(help_text='Наприклад: G-XXXXXXXXXX для GA, або 1234567890 для FB Pixel', max_length=100, verbose_name='ID пікселя')),
                ('code_snippet', models.TextField(help_text='Повний код включно з <script> тегами', verbose_name='Код пікселя')),
                ('placement', models.CharField(choices=[('head', 'Head Section'), ('body_start', 'Body Start'), ('body_end', 'Body End')], default='head', help_text='Де вставити код на сторінці', max_length=20, verbose_name='Розташування')),
                ('is_active', models.BooleanField(default=True, help_text='Чи працює піксель зараз', verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Tracking Pixel',
                'verbose_name_plural': '📊 Tracking Pixels',
                'ordering': ['-created_at'],
                'unique_together': {('pixel_type', 'pixel_id')},
            },
        ),
    ]
