# Generated by Django 4.2.21 on 2025-12-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trackingpixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpixel',
            name='pages',
            field=models.CharField(default='all', help_text="Розділені комами: 'all' для всіх, або home,delivery,about...", max_length=500, verbose_name='Сторінки'),
        ),
    ]
