# Generated by Django 4.2.21 on 2026-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_pages_to_trackingpixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtm_code', models.TextField(blank=True, help_text='Повний код GTM (зазвичай вставляється в head)', null=True, verbose_name='Код Google Tag Manager (GTM)')),
                ('fb_pixel_code', models.TextField(blank=True, help_text='Повний код Facebook Pixel', null=True, verbose_name='Код Facebook Pixel')),
                ('ga_code', models.TextField(blank=True, help_text='Повний код Google Analytics', null=True, verbose_name='Код Google Analytics (GA4)')),
                ('custom_head_code', models.TextField(blank=True, help_text='Будь-які інші скрипти або стилі для секції head', null=True, verbose_name='Додатковий код у <head>')),
                ('custom_body_start_code', models.TextField(blank=True, help_text='Скрипти, що вставляються одразу після відкриваючого тегу body', null=True, verbose_name='Додатковий код на початку <body>')),
                ('custom_body_end_code', models.TextField(blank=True, help_text='Скрипти, що вставляються перед закриваючим тегом body', null=True, verbose_name='Додатковий код у кінці <body>')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': '⚙️ Налаштування сайту',
            },
        ),
    ]
