# Generated by Django 4.2.24 on 2025-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttag_product_is_new_product_is_top_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Максимум 5 товарів для відображення в кінці статті', limit_choices_to={'is_active': True}, to='products.product', verbose_name="Зв'язані товари"),
        ),
    ]
