# Generated by Django 4.2.24 on 2025-10-08 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Токен верифікації'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email підтверджено'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Формат: +380XXXXXXXXX', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Невірний формат телефону. Використовуйте формат +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
