# Generated by Django 4.2.24 on 2025-10-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_turnover_update',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='monthly_turnover',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_wholesale',
            field=models.BooleanField(default=True, help_text='Всі зареєстровані користувачі мають доступ до оптових цін', verbose_name='Оптовий клієнт'),
        ),
    ]
