# Generated by Django 4.2.24 on 2025-10-11 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_turnover_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +380XXXXXXXXX', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Невірний формат телефону. Використовуйте формат +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
